### ISSUE TITLE
i have install wkhtmltopdf in ubuntu but it don't work 

### ISSUE THREAD

**Issue by zhaoyingjun** [jarrekk/imgkit#12]
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    imgkit.from_url('www.aiyangniu.cn','out.jpg')
  File "/usr/local/lib/python2.7/dist-packages/imgkit/api.py", line 19, in from_url
    rtn = IMGKit(url, 'url', options=options, toc=toc, cover=cover, config=config, cover_first=cover_first)
  File "/usr/local/lib/python2.7/dist-packages/imgkit/imgkit.py", line 34, in __init__
    self.config = Config() if not config else config
  File "/usr/local/lib/python2.7/dist-packages/imgkit/config.py", line 36, in __init__
    'http://wkhtmltopdf.org\n'.format(self.wkhtmltoimage))
IOError: No wkhtmltoimage executable found: ""
If this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - http://wkhtmltopdf.org

----------------------------------------------------------

and  i install wkhtmltopdf in my mac use "brew install wkhtmltopdf", there is a error:
Error: No available formula with the name "wkhtmltopdf" 

i have updated my homebrew ,so help me plz.

**Comment by Joramt** [comment]
https://wkhtmltopdf.org/downloads.html

had the same issue, download it from their official web page. The brew seems to have been removed

**Comment by jarrekk** [comment]
This shows you don't have `wkhtmltopdf` in your computer, please install it at <https://wkhtmltopdf.org>.

**Comment by zhaoyingjun** [comment]
Traceback (most recent call last):
  File "create_html.py", line 32, in <module>
    imgkit.from_file(GEN_HTML, str(i)+'.jpg')
  File "/usr/local/lib/python3.4/dist-packages/imgkit/api.py", line 38, in from_file
    return rtn.to_img(output_path)
  File "/usr/local/lib/python3.4/dist-packages/imgkit/imgkit.py", line 243, in to_img
    raise IOError("wkhtmltoimage exited with non-zero code {0}. error:\n{1}\n\n{2}".format(exit_code, stderr, xvfb_error))
OSError: wkhtmltoimage exited with non-zero code -6. error:
QXcbConnection: Could not connect to display 


You need to install xvfb(sudo apt-get install xvfb, yum install xorg-x11-server-Xvfb, etc), then add option: {"xvfb": ""}.

i get a error again, i had install wkhtmltopdf

**Comment by jarrekk** [comment]
Error output says that `You need to install xvfb(sudo apt-get install xvfb, yum install xorg-x11-server-Xvfb, etc), then add option: {"xvfb": ""}.`, because your server is a headless server, please do this.
Thanks.

**Comment by lebanonsky** [comment]
I have a similar issue with Raspbian. I have installed xvfb and added the option, but get 
`IOError: wkhtmltoimage exited with non-zero code 1. error:
xvfb-run: error: Xvfb failed to start`
When running a script. I have X running but do not want to display the generated image on it but save it on disk

**Comment by jarrekk** [comment]
@lebanonsky This is because Raspbian is a headless server, you should confirm if you installed Xvfb, if not please install it:
``` bash
# at ubuntu server, etc.
sudo apt-get install xvfb
# at centos server, etc.
yum install xorg-x11-server-Xvfb
```
then try imgkit code again.

**Comment by lebanonsky** [comment]
Like I said in the comment, I have installed Xvfb and added the option for imgkit. But I also have a Desktop running on the Raspbian, so I think xvfb is clashing with it without the -a parameter.

**Comment by nanodan** [comment]
I have this same issue, apt-get installed xvfb and running imgkit with the xvfb optionb ut getting the failed to start error

**Comment by AmitGamingKing** [comment]
Anyone still having same problem that means you have a headless server you need to install ``pip3 install PyVirtualDisplay`` and then create a fake display 
```python
from pyvirtualdisplay import Display

display = Display(visible=0, size(800,600))
display.start()
imgkit.from_url('google.com', 'img.jpg')
```

And you can take a screenshot from no display (headless)server

**Comment by teckdaniel** [comment]
I'm unable to convert images in my html after doing @AmitGamingKing idea on the xvfb option. Images are blank.

**Comment by Fryziman82** [comment]
> ```shell
> yum install xorg-x11-server-Xvfb
> ```

Failed to set locale, defaulting to C
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>
