### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by zhaoyingjun** [jarrekk/imgkit#14]
mycode:

import imgkit
imgkit.from_file('test.html', 'out.jpg')

but i get a error:

NameError: name 'basestring' is not defined

what mean ?

**Comment by jarrekk** [comment]
@zhaoyingjun Can you show more information about the error? HTML file code, Python environment, etc.

**Comment by eipiminus1** [comment]
I get that error when I run code that uses imgkit with optimizations on.

`python main.py` would work, while  `python -O main.py` does result in the above error.

@zhaoyingjun can you confirm that behavior?
@jarrekk The optimization removes assert statements. The problem probably is here https://github.com/jarrekk/imgkit/blob/763296cc2e81b16b9c3ebd2cd4355ddd02d5ab16/imgkit/imgkit.py#L10-L14 I believe it is not a best practice to rely on assert statements for the code to work.

**Comment by jarrekk** [comment]
@eipiminus1 thanks for the information, it's probably this problem, my original idea is to use the `try` method can avoid importing `six` package, as we all use `six` package, we can use a new way:

``` python
from six import string_types
isinstance(s, string_types)
```

See: https://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility & https://github.com/jarrekk/imgkit/commit/1e7eb203db7ef3ba8344dbbed46d324e077d17c6
