### ISSUE TITLE
Is there a custom image size option?

### ISSUE THREAD

**Issue by Blanketsniffer** [jarrekk/imgkit#18]
it converts to image file just fine but the width is fixed to 1024 px and I could not find a way to change it. 
cropping won't work for me because I need a wider screenshot so I am wondering if there is a way to change the image size.

**Comment by jarrekk** [comment]
@Blanketsniffer 
`wkhtmltopdf/wkhtmltoimage` support `--viewport-size` option, this may help you, later I will add this option to this library or welcome anyone create a PR :)

**Comment by Blanketsniffer** [comment]
Thank you!

**Comment by jarrekk** [comment]
@Blanketsniffer @shennian Perhaps these code can help you:

``` python
options = {'width': 400, 'disable-smart-width'}
imgkit.from_url('https://github.com/trending', 'out.png', options=options)
```
