### ISSUE TITLE
xvfb-run failed to start

### ISSUE THREAD

**Issue by ralliart2004** [jarrekk/imgkit#19]
After using this package, I have run into an issue with the invocation of xvfb-run under the hood. Each virtual headless server xvfb-run spins up will have spin down time. My script calls imgkit synchronously with repetitious invocations of the xvfb-run. The default server it tries is always the same (:99) of which each new one tries this server and fails as the process is still open in memory. A sleep of 100MS has been the work around.

The solution would be to tell xvfb-run with the option `-a, --auto-servernum Try to get a free server number, starting at 99, or the argument to --server-num.` 

Is there a way currently to pass this option down from imgkit to the xvfb-run process being called?

If not, I will submit a PR of this possibility.

**Comment by xtrntr** [comment]
@ralliart2004 i made a PR you might be able to use it if it's helpful

**Comment by jarrekk** [comment]
closed, link to #20
