### ISSUE TITLE
How to use imgkit with a website that needs authentication 

### ISSUE THREAD

**Issue by minhkiller** [jarrekk/imgkit#2]
Hi,

Thanks for your cool library. I am looking for the imgkit api to pass the username / password or cookie into imgkit
Could you please help me?

Thanks,
Minh Tran

**Comment by jarrekk** [comment]
hi @minhkiller 
I find wkhtmltoimage support username/password form post, it has parameters for this, and I wonder using python requests session can access page which needs authentication, then we can use IMGKit to make responded HTML code to image file.
