### ISSUE TITLE
imgkit 设置手机浏览器，生成图片

### ISSUE THREAD

**Issue by shennian** [jarrekk/imgkit#21]
现在默认是用pc来渲染html的

**Comment by jarrekk** [comment]
可以在当中增加一个[参数](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3523#issuecomment-312209735)，在另一个[issue](https://github.com/jarrekk/imgkit/issues/18#issuecomment-341322043)中也有同样的问题，欢迎提交pull request

**Comment by jarrekk** [comment]
Closed, new comment on https://github.com/jarrekk/imgkit/issues/18.
