### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by stscript** [jarrekk/imgkit#3]
When I start the code:
`imgkit.from_string('hello', 'output.jpg')`
it raise the error
<ipython-input-7-a45e19e245eb>** in <module>()
----> 1 imgkit.from_string(r'hello', 'out.jpg')

/opt/anaconda3/lib/python3.6/site-packages/imgkit/api.py in from_string(string, output_path, options, toc, cover, css, config, cover_first)
     55     rtn = IMGKit(string, 'string', options=options, toc=toc, cover=cover, css=css,
     56                  config=config, cover_first=cover_first)
---> 57     return rtn.to_img(output_path)
     58 
     59 

/opt/anaconda3/lib/python3.6/site-packages/imgkit/imgkit.py in to_img(self, path)
    240             try:
    241                 with codecs.open(path) as f:
--> 242                     text = f.read(4)
    243                     if text == '':
    244                         raise IOError('Command failed: %s\n'

/opt/anaconda3/lib/python3.6/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by jarrekk** [comment]
Thanks for helping improving this lib, this is python3.6 string encoding bug, I fixed it at new version
[IMGKit](https://pypi.python.org/pypi/imgkit/0.0.5)

**Comment by MaxwellPayne** [comment]
I think your last bug fix might have broken the module for Python 2.x versions. I'm running Python 2.7.11 and this is the error I get when my program runs into your patch:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Max/tmp/djangoenv/lib/python2.7/site-packages/imgkit/api.py", line 57, in from_string
    return rtn.to_img(output_path)
  File "/Users/Max/tmp/djangoenv/lib/python2.7/site-packages/imgkit/imgkit.py", line 242, in to_img
    text = f.read(4).encode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
```

I don't have this problem with `imgkit==0.0.4`.

**Comment by jarrekk** [comment]
@MaxwellPayne Thanks 
I have fixed this bug, please try new version, this code is used to check if file is really generated.
