### ISSUE TITLE
Poor Rendering Quality / Poor Image Quality

### ISSUE THREAD

**Issue by bananakiu** [jarrekk/imgkit#30]
The image quality, even when set to max, isn't very good. Is there a way to improve this?

**Comment by jarrekk** [comment]
`imgkit` doesn't help on the image quality, `wkhtmltoimage` is the key program to make the image, you may ask help for https://github.com/wkhtmltopdf/wkhtmltopdf/issues. A related issue: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3611
