### ISSUE TITLE
Zooming in

### ISSUE THREAD

**Issue by 0xYonas** [jarrekk/imgkit#32]
Is there anyway to zoom up in a webpage? Like to 125% instead of 100%
Also if my webpage isnt fully loaded, what do you reccomend I do.

**Comment by jarrekk** [comment]
You can go to [`wkhtmltoimage`](https://github.com/wkhtmltopdf/wkhtmltopdf/issues) for help, if no maybe PIL can help after the image is generated.

> Also if my webpage isnt fully loaded, what do you reccomend I do.

Maybe you can get the HTML file code and use the code to generate the image.
