### ISSUE TITLE
Link to wkhtmltopdf's manual is broken

### ISSUE THREAD

**Issue by jonatasleon** [jarrekk/imgkit#34]
On README.md the link that points to wkhtmltopdf's manual returns as invalid page. 

To solve my questions I used this link: https://wkhtmltopdf.org/usage/wkhtmltopdf.txt

**Comment by jarrekk** [comment]
Updated at https://github.com/jarrekk/imgkit/commit/26a5093a4d2de858165207fdeac003573c87de8b, thanks and welcome for a pull request! :)
