### ISSUE TITLE
How do i prevent output?

### ISSUE THREAD

**Issue by NekoTony** [jarrekk/imgkit#37]
```Nov 28 12:25:56 Alice python3.7[28666]: [1.1K blob data]
Nov 28 12:25:56 Alice python3.7[28666]: [205B blob data]
Nov 28 12:26:07 Alice python3.7[28666]: Loading page (1/2)
```

I want to disable blob data output.

```
by = imgkit.from_string(
            html, False, options={
                "width": 444,
                "height": 250,
                "crop-w": 444
            })
return by
```

**Comment by VincentJonathan** [comment]
Having same issue, currently using solution from [here](https://codereview.stackexchange.com/questions/25417/is-there-a-better-way-to-make-a-function-silent-on-need)

Your code will look like this
`
import imgkit
import os
import sys

class NoStdStreams(object):
    def __init__(self,stdout = None, stderr = None):
        self.devnull = open(os.devnull,'w')
        self._stdout = stdout or self.devnull or sys.stdout
        self._stderr = stderr or self.devnull or sys.stderr

    def __enter__(self):
        self.old_stdout, self.old_stderr = sys.stdout, sys.stderr
        self.old_stdout.flush(); self.old_stderr.flush()
        sys.stdout, sys.stderr = self._stdout, self._stderr

    def __exit__(self, exc_type, exc_value, traceback):
        self._stdout.flush(); self._stderr.flush()
        sys.stdout = self.old_stdout
        sys.stderr = self.old_stderr
        self.devnull.close()

with NoStdStreams():
    by = imgkit.from_string(html, False)
`

**Comment by VincentJonathan** [comment]
Having same issue, currently using solution from [here](https://codereview.stackexchange.com/questions/25417/is-there-a-better-way-to-make-a-function-silent-on-need)

Your code will look like this


```
import imgkit
import os
import sys

class NoStdStreams(object):
    def __init__(self,stdout = None, stderr = None):
        self.devnull = open(os.devnull,'w')
        self._stdout = stdout or self.devnull or sys.stdout
        self._stderr = stderr or self.devnull or sys.stderr

    def __enter__(self):
        self.old_stdout, self.old_stderr = sys.stdout, sys.stderr
        self.old_stdout.flush(); self.old_stderr.flush()
        sys.stdout, sys.stderr = self._stdout, self._stderr

    def __exit__(self, exc_type, exc_value, traceback):
        self._stdout.flush(); self._stderr.flush()
        sys.stdout = self.old_stdout
        sys.stderr = self.old_stderr
        self.devnull.close()

with NoStdStreams():
    by = imgkit.from_string(html, False)

**Comment by NekoTony** [comment]
Thank you!
