### ISSUE TITLE
on macos | Error: No available formula with the name "wkhtmltopdf" 

### ISSUE THREAD

**Issue by julescript** [jarrekk/imgkit#39]
when i try `brew install wkhtmltopdf` i get this:

`
Error: No available formula with the name "wkhtmltopdf" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
`

anyone can help?

**Comment by julescript** [comment]
fixed by `brew install homebrew/cask/wkhtmltopdf`

**Comment by ehmatthes** [comment]
I ran into the same issue, and resolved it with `brew cask install wkhtmltopdf`.
