### ISSUE TITLE
INFO: Could not find files for the given pattern(s)

### ISSUE THREAD

**Issue by backslash** [jarrekk/imgkit#42]
OS: Windows

``` 
ip = 127.0.0.1

		options = {
			'quiet': ''
		}
		img = imgkit.from_url(f'http://{ip}', f"sites\\{ip}.png", options=options)

```
Will sometimes return `INFO: Could not find files for the given pattern(s)` , any idea on whats causing this? Everything is correctly added to path.

**Comment by WiseNat** [comment]
OS: Windows

```Python
options = {"quiet": ""}
config = imgkit.config(wkhtmltoimage="wkhtmltopdf/bin/wkhtmltoimage.exe")
imgkit.from_string(html_string, "data/result.png", config=config, options=options)
```

Whenever the config method on line 2 is run, `INFO: Could not find files for the given pattern(s)` is outputted in terminal.

**Comment by WiseNat** [comment]
It wasn't a solution - just another way that output occurs.

I doubt it's supposed to do that at all honestly since the code works fine.
