### ISSUE TITLE
How to set the DPI of output image?

### ISSUE THREAD

**Issue by YuLiu-lab** [jarrekk/imgkit#47]
My code is as follows:
options = {
        "quiet": "",
        "width": 460,
        "dpi": 120,
    }
imgkit.from_file("render.html", 'out.jpg', options=options)
But after I run it, PyCharm display：
Unknown long argument --dpi

**Comment by jarrekk** [comment]
There is no `dpi` option in `wkhtmltoimage` help page, please refer: https://stackoverflow.com/questions/9174338/programmatically-change-image-resolution
