### ISSUE TITLE
老哥，你这个README是抄的Python-PDFKit项目的readme吗？

### ISSUE THREAD

**Issue by Bob-Yuan** [jarrekk/imgkit#48]
You can pass a list with multiple URLs or files:

imgkit.from_url(['google.com', 'yandex.ru', 'engadget.com'], 'out.jpg')
imgkit.from_file(['file1.html', 'file2.html'], 'out.jpg')

Python-PDFKit可以这样用，你这个转图片不支持这样用啊！
。。。

**Comment by jarrekk** [comment]
`wkhtmltoimage` doesn't support this feature, remove it from readme.
