### ISSUE TITLE
encoding is not supported?

### ISSUE THREAD

**Issue by dimab0** [jarrekk/imgkit#5]
imgkit.from_string(html, 'out.jpg', config=config_image)

Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-18-b2078331945f> in <module>()
----> 1 imgkit.from_string(html, 'out.jpg', config=config_image)

C:\Users\Trader\Anaconda3\lib\site-packages\imgkit-0.0.7-py3.5.egg\imgkit\api.py in from_string(string, output_path, options, toc, cover, css, config, cover_first)
     55     rtn = IMGKit(string, 'string', options=options, toc=toc, cover=cover, css=css,
     56                  config=config, cover_first=cover_first)
---> 57     return rtn.to_img(output_path)
     58 
     59 

C:\Users\Trader\Anaconda3\lib\site-packages\imgkit-0.0.7-py3.5.egg\imgkit\imgkit.py in to_img(self, path)
    243                         text = f.read(4)
    244                     else:
--> 245                         text = f.read(4).encode()
    246                     if text == '':
    247                         raise IOError('Command failed: %s\n'

C:\Users\Trader\Anaconda3\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 786: character maps to <undefined>

**Comment by henkjannl** [comment]
Same or similar situation here (Ubuntu 17.04, Python 3.5.3):

Traceback (most recent call last):
  File "TestScheurkalender.py", line 218, in <module>
    imgkit.from_string(s, outputImage, options = options)
  File "/home/henkjan/.local/lib/python3.5/site-packages/imgkit/api.py", line 57, in from_string
    return rtn.to_img(output_path)
  File "/home/henkjan/.local/lib/python3.5/site-packages/imgkit/imgkit.py", line 245, in to_img
    text = f.read(4).encode()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by jarrekk** [comment]
New version may fix this bug, thanks.
