### ISSUE TITLE
ImgKit does not render images in local file

### ISSUE THREAD

**Issue by maciclol** [jarrekk/imgkit#58]
Hi,

I am trying to convert a local HTML file into a jpeg. Everything works, except for the image in the HTML document, which doesn't show up. I've tried everything, including setting the img src to base64. The image still doesn't show up in the final jpeg.

I also read somewhere that I should add a header <meta content="text/html; charset=utf-8" http-equiv="Content-type"> to my document to make it work, but it doesn't help.

**Comment by maciclol** [comment]
nvm got it

**Comment by tranmanhhung** [comment]
> nvm got it

how complete it, please
