### ISSUE TITLE
from_string() got an unexpected keyword argument 'config'

### ISSUE THREAD

**Issue by CipherFox** [jarrekk/imgkit#68]
I have two issues to report. One is a product of the other.

My code for the first one is as follows:

```py
wkhtmltoimage_binaries = imgkit.config(wkhtmltoimage = '/app/bin/wkhtmltoimage')
img = imgkit.from_string('<body>hi</body>', False, config = wkhtmltoimage_binaries)
```

The resulting error is as follows:

```
TypeError: from_string() got an unexpected keyword argument 'config'
```

This confused me, as it has worked for a long time until just recently. Your readme file also mentions `config` being a keyword argument. Nevertheless, I edited my code to the following in hopes that it might detect the binaries automatically:

```py
img = imgkit.from_string('<body>hi</body>', False)
```

It did not detect them automatically. In fact, the new error seems to communicate the presence of a bug. The error is as follows:

```
OSError: No wkhtmltoimage executable found: "command not found"
```

So I have two questions:

1. Are we no longer able to configure imgkit to where we can specify the location of the wkhtmltoimage binaries?

2. Following `No wkhtmltoimage executable found:`, isn't it meant to display the directory that it attempted to read from, rather than "command not found"?

```
OS: Ubuntu 20.04.2 LTS (Focal Fossa)
```

**Comment by jarrekk** [comment]
@CipherFox Great findings! I renamed `config` to `configuration` to avoid function name & parameter in https://github.com/jarrekk/imgkit/blob/master/src/imgkit/api.py, will fix it in the next version.
You can give the `configuration` parameter now.
