### ISSUE TITLE
Is still updated this proyect?

### ISSUE THREAD

**Issue by mesaglio** [jarrekk/imgkit#90]
Hi, there 👋 !

I have a question, this have a hard dependencie with [wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf) software. I understand this is archived, so no more feature or security updates are being applied.

This you think change this dependency or some other alternative?

Thanks!

**Comment by mesaglio** [comment]
@jarrekk

**Comment by jarrekk** [comment]
Sorry for the late reply, currently I don't plan to change it cause I don't have enough time, but if you are interested on this, feel free to do it. :)
